FROM oven/bun:1.2.4 AS base

# Install global deps
COPY package.json ./
COPY bun.lock ./
RUN bun i

# Install all internal deps
COPY packages/db/package.json ./packages/db/package.json
RUN bun i

# Copy packages
COPY packages/db ./packages/db

# Set environment variables
ENV DATABASE_URL postgresql://bngc:bngc@db/bngc

# Run deploy scripts
CMD bun -F @bngc/db deploy